# Generated by Django 4.2.6 on 2024-01-21 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Gym_split',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('split_name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Muscle_strength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Gym_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('no_of_days', models.IntegerField(default=0)),
                ('dob', models.CharField(max_length=20)),
                ('phone_number', models.IntegerField()),
                ('image', models.ImageField(default='users_profile_images/image.png', upload_to='users_profile_images/')),
                ('weight', models.IntegerField()),
                ('height', models.IntegerField()),
                ('date_of_joining', models.DateTimeField(auto_now_add=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(default='', max_length=100)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gym.address')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gym.gender')),
                ('gym_split', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gym.gym_split')),
                ('muscle_strength', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gym.muscle_strength')),
            ],
        ),
    ]
