# Generated by Django 4.2.6 on 2024-01-29 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0002_alter_gym_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gym_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=20)),
                ('phone_number', models.IntegerField()),
                ('image', models.ImageField(default='images/find_user.png', upload_to='admin_images/')),
                ('date_of_joining', models.DateTimeField(auto_now_add=True)),
                ('email', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gym.address')),
            ],
        ),
    ]
