# Generated by Django 5.2.6 on 2025-09-12 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0003_gym_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym_user',
            name='dob',
            field=models.DateField(),
        ),
        migrations.DeleteModel(
            name='Gym_admin',
        ),
    ]
